/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nlp_Parser */

#ifndef _Included_cn_nlp_Parser
#define _Included_cn_nlp_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nlp_Parser
 * Method:    parseSentence
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_nlp_Parser_parseSentence
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_nlp_Parser
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_nlp_Parser_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_nlp_Parser
 * Method:    parseFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_nlp_Parser_parseFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
